# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/shigerukurokawa/Codes/nncp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/shigerukurokawa/Codes/nncp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shigerukurokawa/Codes/nncp/CMakeFiles /Users/shigerukurokawa/Codes/nncp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shigerukurokawa/Codes/nncp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named metal_shaders

# Build rule for target.
metal_shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 metal_shaders
.PHONY : metal_shaders

# fast build rule for target.
metal_shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/metal_shaders.dir/build.make CMakeFiles/metal_shaders.dir/build
.PHONY : metal_shaders/fast

#=============================================================================
# Target rules for targets named nncp-metal

# Build rule for target.
nncp-metal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nncp-metal
.PHONY : nncp-metal

# fast build rule for target.
nncp-metal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/build
.PHONY : nncp-metal/fast

#=============================================================================
# Target rules for targets named nncp-diagnostics

# Build rule for target.
nncp-diagnostics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nncp-diagnostics
.PHONY : nncp-diagnostics

# fast build rule for target.
nncp-diagnostics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/build
.PHONY : nncp-diagnostics/fast

#=============================================================================
# Target rules for targets named test-compression-integration

# Build rule for target.
test-compression-integration: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-compression-integration
.PHONY : test-compression-integration

# fast build rule for target.
test-compression-integration/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/build
.PHONY : test-compression-integration/fast

#=============================================================================
# Target rules for targets named cuda-compatibility-tests

# Build rule for target.
cuda-compatibility-tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cuda-compatibility-tests
.PHONY : cuda-compatibility-tests

# fast build rule for target.
cuda-compatibility-tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/build
.PHONY : cuda-compatibility-tests/fast

#=============================================================================
# Target rules for targets named nncp_tests

# Build rule for target.
nncp_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nncp_tests
.PHONY : nncp_tests

# fast build rule for target.
nncp_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/nncp_tests.dir/build.make tests/CMakeFiles/nncp_tests.dir/build
.PHONY : nncp_tests/fast

#=============================================================================
# Target rules for targets named test_bpe_tokenizer

# Build rule for target.
test_bpe_tokenizer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bpe_tokenizer
.PHONY : test_bpe_tokenizer

# fast build rule for target.
test_bpe_tokenizer/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_bpe_tokenizer.dir/build.make tests/CMakeFiles/test_bpe_tokenizer.dir/build
.PHONY : test_bpe_tokenizer/fast

#=============================================================================
# Target rules for targets named test_sequence_manager

# Build rule for target.
test_sequence_manager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sequence_manager
.PHONY : test_sequence_manager

# fast build rule for target.
test_sequence_manager/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_sequence_manager.dir/build.make tests/CMakeFiles/test_sequence_manager.dir/build
.PHONY : test_sequence_manager/fast

#=============================================================================
# Target rules for targets named test_coreml_loader

# Build rule for target.
test_coreml_loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_coreml_loader
.PHONY : test_coreml_loader

# fast build rule for target.
test_coreml_loader/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_coreml_loader.dir/build.make tests/CMakeFiles/test_coreml_loader.dir/build
.PHONY : test_coreml_loader/fast

#=============================================================================
# Target rules for targets named test_mps_attention

# Build rule for target.
test_mps_attention: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mps_attention
.PHONY : test_mps_attention

# fast build rule for target.
test_mps_attention/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mps_attention.dir/build.make tests/CMakeFiles/test_mps_attention.dir/build
.PHONY : test_mps_attention/fast

#=============================================================================
# Target rules for targets named test_mps_lstm

# Build rule for target.
test_mps_lstm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mps_lstm
.PHONY : test_mps_lstm

# fast build rule for target.
test_mps_lstm/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mps_lstm.dir/build.make tests/CMakeFiles/test_mps_lstm.dir/build
.PHONY : test_mps_lstm/fast

#=============================================================================
# Target rules for targets named test_mps_transformer

# Build rule for target.
test_mps_transformer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mps_transformer
.PHONY : test_mps_transformer

# fast build rule for target.
test_mps_transformer/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_mps_transformer.dir/build.make tests/CMakeFiles/test_mps_transformer.dir/build
.PHONY : test_mps_transformer/fast

#=============================================================================
# Target rules for targets named test_compression_selector

# Build rule for target.
test_compression_selector: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_compression_selector
.PHONY : test_compression_selector

# fast build rule for target.
test_compression_selector/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_compression_selector.dir/build.make tests/CMakeFiles/test_compression_selector.dir/build
.PHONY : test_compression_selector/fast

#=============================================================================
# Target rules for targets named test_enhanced_format

# Build rule for target.
test_enhanced_format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_enhanced_format
.PHONY : test_enhanced_format

# fast build rule for target.
test_enhanced_format/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_enhanced_format.dir/build.make tests/CMakeFiles/test_enhanced_format.dir/build
.PHONY : test_enhanced_format/fast

#=============================================================================
# Target rules for targets named test_quality_validator

# Build rule for target.
test_quality_validator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_quality_validator
.PHONY : test_quality_validator

# fast build rule for target.
test_quality_validator/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_quality_validator.dir/build.make tests/CMakeFiles/test_quality_validator.dir/build
.PHONY : test_quality_validator/fast

#=============================================================================
# Target rules for targets named test_performance_monitor

# Build rule for target.
test_performance_monitor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_performance_monitor
.PHONY : test_performance_monitor

# fast build rule for target.
test_performance_monitor/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_performance_monitor.dir/build.make tests/CMakeFiles/test_performance_monitor.dir/build
.PHONY : test_performance_monitor/fast

src/metal/algorithm_router.o: src/metal/algorithm_router.c.o
.PHONY : src/metal/algorithm_router.o

# target to build an object file
src/metal/algorithm_router.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/algorithm_router.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/metal/algorithm_router.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/algorithm_router.c.o
.PHONY : src/metal/algorithm_router.c.o

src/metal/algorithm_router.i: src/metal/algorithm_router.c.i
.PHONY : src/metal/algorithm_router.i

# target to preprocess a source file
src/metal/algorithm_router.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/algorithm_router.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/metal/algorithm_router.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/algorithm_router.c.i
.PHONY : src/metal/algorithm_router.c.i

src/metal/algorithm_router.s: src/metal/algorithm_router.c.s
.PHONY : src/metal/algorithm_router.s

# target to generate assembly for a file
src/metal/algorithm_router.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/algorithm_router.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/metal/algorithm_router.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/algorithm_router.c.s
.PHONY : src/metal/algorithm_router.c.s

src/metal/compression_integration.o: src/metal/compression_integration.c.o
.PHONY : src/metal/compression_integration.o

# target to build an object file
src/metal/compression_integration.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/compression_integration.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/metal/compression_integration.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/compression_integration.c.o
.PHONY : src/metal/compression_integration.c.o

src/metal/compression_integration.i: src/metal/compression_integration.c.i
.PHONY : src/metal/compression_integration.i

# target to preprocess a source file
src/metal/compression_integration.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/compression_integration.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/metal/compression_integration.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/compression_integration.c.i
.PHONY : src/metal/compression_integration.c.i

src/metal/compression_integration.s: src/metal/compression_integration.c.s
.PHONY : src/metal/compression_integration.s

# target to generate assembly for a file
src/metal/compression_integration.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/compression_integration.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/metal/compression_integration.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/compression_integration.c.s
.PHONY : src/metal/compression_integration.c.s

src/metal/compression_selector_stub.o: src/metal/compression_selector_stub.c.o
.PHONY : src/metal/compression_selector_stub.o

# target to build an object file
src/metal/compression_selector_stub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/compression_selector_stub.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/compression_selector_stub.c.o
.PHONY : src/metal/compression_selector_stub.c.o

src/metal/compression_selector_stub.i: src/metal/compression_selector_stub.c.i
.PHONY : src/metal/compression_selector_stub.i

# target to preprocess a source file
src/metal/compression_selector_stub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/compression_selector_stub.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/compression_selector_stub.c.i
.PHONY : src/metal/compression_selector_stub.c.i

src/metal/compression_selector_stub.s: src/metal/compression_selector_stub.c.s
.PHONY : src/metal/compression_selector_stub.s

# target to generate assembly for a file
src/metal/compression_selector_stub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/compression_selector_stub.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/compression_selector_stub.c.s
.PHONY : src/metal/compression_selector_stub.c.s

src/metal/nncp_diagnostics.o: src/metal/nncp_diagnostics.c.o
.PHONY : src/metal/nncp_diagnostics.o

# target to build an object file
src/metal/nncp_diagnostics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/metal/nncp_diagnostics.c.o
.PHONY : src/metal/nncp_diagnostics.c.o

src/metal/nncp_diagnostics.i: src/metal/nncp_diagnostics.c.i
.PHONY : src/metal/nncp_diagnostics.i

# target to preprocess a source file
src/metal/nncp_diagnostics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/metal/nncp_diagnostics.c.i
.PHONY : src/metal/nncp_diagnostics.c.i

src/metal/nncp_diagnostics.s: src/metal/nncp_diagnostics.c.s
.PHONY : src/metal/nncp_diagnostics.s

# target to generate assembly for a file
src/metal/nncp_diagnostics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/metal/nncp_diagnostics.c.s
.PHONY : src/metal/nncp_diagnostics.c.s

src/metal/nncp_metal.o: src/metal/nncp_metal.c.o
.PHONY : src/metal/nncp_metal.o

# target to build an object file
src/metal/nncp_metal.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/nncp_metal.c.o
.PHONY : src/metal/nncp_metal.c.o

src/metal/nncp_metal.i: src/metal/nncp_metal.c.i
.PHONY : src/metal/nncp_metal.i

# target to preprocess a source file
src/metal/nncp_metal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/nncp_metal.c.i
.PHONY : src/metal/nncp_metal.c.i

src/metal/nncp_metal.s: src/metal/nncp_metal.c.s
.PHONY : src/metal/nncp_metal.s

# target to generate assembly for a file
src/metal/nncp_metal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/nncp_metal.c.s
.PHONY : src/metal/nncp_metal.c.s

src/metal/nncp_original_port.o: src/metal/nncp_original_port.c.o
.PHONY : src/metal/nncp_original_port.o

# target to build an object file
src/metal/nncp_original_port.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/nncp_original_port.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/nncp_original_port.c.o
.PHONY : src/metal/nncp_original_port.c.o

src/metal/nncp_original_port.i: src/metal/nncp_original_port.c.i
.PHONY : src/metal/nncp_original_port.i

# target to preprocess a source file
src/metal/nncp_original_port.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/nncp_original_port.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/nncp_original_port.c.i
.PHONY : src/metal/nncp_original_port.c.i

src/metal/nncp_original_port.s: src/metal/nncp_original_port.c.s
.PHONY : src/metal/nncp_original_port.s

# target to generate assembly for a file
src/metal/nncp_original_port.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/nncp_original_port.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/nncp_original_port.c.s
.PHONY : src/metal/nncp_original_port.c.s

src/metal/wrapper/compute_kernels.o: src/metal/wrapper/compute_kernels.mm.o
.PHONY : src/metal/wrapper/compute_kernels.o

# target to build an object file
src/metal/wrapper/compute_kernels.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/compute_kernels.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/compute_kernels.mm.o
.PHONY : src/metal/wrapper/compute_kernels.mm.o

src/metal/wrapper/compute_kernels.i: src/metal/wrapper/compute_kernels.mm.i
.PHONY : src/metal/wrapper/compute_kernels.i

# target to preprocess a source file
src/metal/wrapper/compute_kernels.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/compute_kernels.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/compute_kernels.mm.i
.PHONY : src/metal/wrapper/compute_kernels.mm.i

src/metal/wrapper/compute_kernels.s: src/metal/wrapper/compute_kernels.mm.s
.PHONY : src/metal/wrapper/compute_kernels.s

# target to generate assembly for a file
src/metal/wrapper/compute_kernels.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/compute_kernels.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/compute_kernels.mm.s
.PHONY : src/metal/wrapper/compute_kernels.mm.s

src/metal/wrapper/memory_manager.o: src/metal/wrapper/memory_manager.mm.o
.PHONY : src/metal/wrapper/memory_manager.o

# target to build an object file
src/metal/wrapper/memory_manager.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/memory_manager.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/memory_manager.mm.o
.PHONY : src/metal/wrapper/memory_manager.mm.o

src/metal/wrapper/memory_manager.i: src/metal/wrapper/memory_manager.mm.i
.PHONY : src/metal/wrapper/memory_manager.i

# target to preprocess a source file
src/metal/wrapper/memory_manager.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/memory_manager.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/memory_manager.mm.i
.PHONY : src/metal/wrapper/memory_manager.mm.i

src/metal/wrapper/memory_manager.s: src/metal/wrapper/memory_manager.mm.s
.PHONY : src/metal/wrapper/memory_manager.s

# target to generate assembly for a file
src/metal/wrapper/memory_manager.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/memory_manager.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/memory_manager.mm.s
.PHONY : src/metal/wrapper/memory_manager.mm.s

src/metal/wrapper/metal_buffers.o: src/metal/wrapper/metal_buffers.mm.o
.PHONY : src/metal/wrapper/metal_buffers.o

# target to build an object file
src/metal/wrapper/metal_buffers.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/metal_buffers.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/metal_buffers.mm.o
.PHONY : src/metal/wrapper/metal_buffers.mm.o

src/metal/wrapper/metal_buffers.i: src/metal/wrapper/metal_buffers.mm.i
.PHONY : src/metal/wrapper/metal_buffers.i

# target to preprocess a source file
src/metal/wrapper/metal_buffers.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/metal_buffers.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/metal_buffers.mm.i
.PHONY : src/metal/wrapper/metal_buffers.mm.i

src/metal/wrapper/metal_buffers.s: src/metal/wrapper/metal_buffers.mm.s
.PHONY : src/metal/wrapper/metal_buffers.s

# target to generate assembly for a file
src/metal/wrapper/metal_buffers.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/metal_buffers.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/metal_buffers.mm.s
.PHONY : src/metal/wrapper/metal_buffers.mm.s

src/metal/wrapper/metal_context.o: src/metal/wrapper/metal_context.mm.o
.PHONY : src/metal/wrapper/metal_context.o

# target to build an object file
src/metal/wrapper/metal_context.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/metal_context.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/metal_context.mm.o
.PHONY : src/metal/wrapper/metal_context.mm.o

src/metal/wrapper/metal_context.i: src/metal/wrapper/metal_context.mm.i
.PHONY : src/metal/wrapper/metal_context.i

# target to preprocess a source file
src/metal/wrapper/metal_context.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/metal_context.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/metal_context.mm.i
.PHONY : src/metal/wrapper/metal_context.mm.i

src/metal/wrapper/metal_context.s: src/metal/wrapper/metal_context.mm.s
.PHONY : src/metal/wrapper/metal_context.s

# target to generate assembly for a file
src/metal/wrapper/metal_context.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/metal_context.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/metal_context.mm.s
.PHONY : src/metal/wrapper/metal_context.mm.s

src/metal/wrapper/metal_kernels.o: src/metal/wrapper/metal_kernels.mm.o
.PHONY : src/metal/wrapper/metal_kernels.o

# target to build an object file
src/metal/wrapper/metal_kernels.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/metal_kernels.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/metal_kernels.mm.o
.PHONY : src/metal/wrapper/metal_kernels.mm.o

src/metal/wrapper/metal_kernels.i: src/metal/wrapper/metal_kernels.mm.i
.PHONY : src/metal/wrapper/metal_kernels.i

# target to preprocess a source file
src/metal/wrapper/metal_kernels.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/metal_kernels.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/metal_kernels.mm.i
.PHONY : src/metal/wrapper/metal_kernels.mm.i

src/metal/wrapper/metal_kernels.s: src/metal/wrapper/metal_kernels.mm.s
.PHONY : src/metal/wrapper/metal_kernels.s

# target to generate assembly for a file
src/metal/wrapper/metal_kernels.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/metal_kernels.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/metal_kernels.mm.s
.PHONY : src/metal/wrapper/metal_kernels.mm.s

src/metal/wrapper/neural_engine.o: src/metal/wrapper/neural_engine.mm.o
.PHONY : src/metal/wrapper/neural_engine.o

# target to build an object file
src/metal/wrapper/neural_engine.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/neural_engine.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/neural_engine.mm.o
.PHONY : src/metal/wrapper/neural_engine.mm.o

src/metal/wrapper/neural_engine.i: src/metal/wrapper/neural_engine.mm.i
.PHONY : src/metal/wrapper/neural_engine.i

# target to preprocess a source file
src/metal/wrapper/neural_engine.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/neural_engine.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/neural_engine.mm.i
.PHONY : src/metal/wrapper/neural_engine.mm.i

src/metal/wrapper/neural_engine.s: src/metal/wrapper/neural_engine.mm.s
.PHONY : src/metal/wrapper/neural_engine.s

# target to generate assembly for a file
src/metal/wrapper/neural_engine.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/metal/wrapper/neural_engine.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/metal/wrapper/neural_engine.mm.s
.PHONY : src/metal/wrapper/neural_engine.mm.s

src/neural/compatibility/cuda_math_compat.o: src/neural/compatibility/cuda_math_compat.c.o
.PHONY : src/neural/compatibility/cuda_math_compat.o

# target to build an object file
src/neural/compatibility/cuda_math_compat.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/compatibility/cuda_math_compat.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/compatibility/cuda_math_compat.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/compatibility/cuda_math_compat.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/src/neural/compatibility/cuda_math_compat.c.o
.PHONY : src/neural/compatibility/cuda_math_compat.c.o

src/neural/compatibility/cuda_math_compat.i: src/neural/compatibility/cuda_math_compat.c.i
.PHONY : src/neural/compatibility/cuda_math_compat.i

# target to preprocess a source file
src/neural/compatibility/cuda_math_compat.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/compatibility/cuda_math_compat.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/compatibility/cuda_math_compat.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/compatibility/cuda_math_compat.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/src/neural/compatibility/cuda_math_compat.c.i
.PHONY : src/neural/compatibility/cuda_math_compat.c.i

src/neural/compatibility/cuda_math_compat.s: src/neural/compatibility/cuda_math_compat.c.s
.PHONY : src/neural/compatibility/cuda_math_compat.s

# target to generate assembly for a file
src/neural/compatibility/cuda_math_compat.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/compatibility/cuda_math_compat.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/compatibility/cuda_math_compat.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/compatibility/cuda_math_compat.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/src/neural/compatibility/cuda_math_compat.c.s
.PHONY : src/neural/compatibility/cuda_math_compat.c.s

src/neural/config/cuda_profiles.o: src/neural/config/cuda_profiles.c.o
.PHONY : src/neural/config/cuda_profiles.o

# target to build an object file
src/neural/config/cuda_profiles.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/config/cuda_profiles.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/config/cuda_profiles.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/config/cuda_profiles.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/src/neural/config/cuda_profiles.c.o
.PHONY : src/neural/config/cuda_profiles.c.o

src/neural/config/cuda_profiles.i: src/neural/config/cuda_profiles.c.i
.PHONY : src/neural/config/cuda_profiles.i

# target to preprocess a source file
src/neural/config/cuda_profiles.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/config/cuda_profiles.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/config/cuda_profiles.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/config/cuda_profiles.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/src/neural/config/cuda_profiles.c.i
.PHONY : src/neural/config/cuda_profiles.c.i

src/neural/config/cuda_profiles.s: src/neural/config/cuda_profiles.c.s
.PHONY : src/neural/config/cuda_profiles.s

# target to generate assembly for a file
src/neural/config/cuda_profiles.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/config/cuda_profiles.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/config/cuda_profiles.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/config/cuda_profiles.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/src/neural/config/cuda_profiles.c.s
.PHONY : src/neural/config/cuda_profiles.c.s

src/neural/context/dynamic_context.o: src/neural/context/dynamic_context.c.o
.PHONY : src/neural/context/dynamic_context.o

# target to build an object file
src/neural/context/dynamic_context.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/context/dynamic_context.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/context/dynamic_context.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/context/dynamic_context.c.o
.PHONY : src/neural/context/dynamic_context.c.o

src/neural/context/dynamic_context.i: src/neural/context/dynamic_context.c.i
.PHONY : src/neural/context/dynamic_context.i

# target to preprocess a source file
src/neural/context/dynamic_context.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/context/dynamic_context.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/context/dynamic_context.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/context/dynamic_context.c.i
.PHONY : src/neural/context/dynamic_context.c.i

src/neural/context/dynamic_context.s: src/neural/context/dynamic_context.c.s
.PHONY : src/neural/context/dynamic_context.s

# target to generate assembly for a file
src/neural/context/dynamic_context.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/context/dynamic_context.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/context/dynamic_context.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/context/dynamic_context.c.s
.PHONY : src/neural/context/dynamic_context.c.s

src/neural/error/cuda_error_handler.o: src/neural/error/cuda_error_handler.c.o
.PHONY : src/neural/error/cuda_error_handler.o

# target to build an object file
src/neural/error/cuda_error_handler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/error/cuda_error_handler.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/error/cuda_error_handler.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/src/neural/error/cuda_error_handler.c.o
.PHONY : src/neural/error/cuda_error_handler.c.o

src/neural/error/cuda_error_handler.i: src/neural/error/cuda_error_handler.c.i
.PHONY : src/neural/error/cuda_error_handler.i

# target to preprocess a source file
src/neural/error/cuda_error_handler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/error/cuda_error_handler.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/error/cuda_error_handler.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/src/neural/error/cuda_error_handler.c.i
.PHONY : src/neural/error/cuda_error_handler.c.i

src/neural/error/cuda_error_handler.s: src/neural/error/cuda_error_handler.c.s
.PHONY : src/neural/error/cuda_error_handler.s

# target to generate assembly for a file
src/neural/error/cuda_error_handler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/error/cuda_error_handler.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/error/cuda_error_handler.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/src/neural/error/cuda_error_handler.c.s
.PHONY : src/neural/error/cuda_error_handler.c.s

src/neural/handlers/small_file_handler.o: src/neural/handlers/small_file_handler.c.o
.PHONY : src/neural/handlers/small_file_handler.o

# target to build an object file
src/neural/handlers/small_file_handler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/handlers/small_file_handler.c.o
.PHONY : src/neural/handlers/small_file_handler.c.o

src/neural/handlers/small_file_handler.i: src/neural/handlers/small_file_handler.c.i
.PHONY : src/neural/handlers/small_file_handler.i

# target to preprocess a source file
src/neural/handlers/small_file_handler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/handlers/small_file_handler.c.i
.PHONY : src/neural/handlers/small_file_handler.c.i

src/neural/handlers/small_file_handler.s: src/neural/handlers/small_file_handler.c.s
.PHONY : src/neural/handlers/small_file_handler.s

# target to generate assembly for a file
src/neural/handlers/small_file_handler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/handlers/small_file_handler.c.s
.PHONY : src/neural/handlers/small_file_handler.c.s

src/neural/integration/neural_bridge.o: src/neural/integration/neural_bridge.mm.o
.PHONY : src/neural/integration/neural_bridge.o

# target to build an object file
src/neural/integration/neural_bridge.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/integration/neural_bridge.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/integration/neural_bridge.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/integration/neural_bridge.mm.o
.PHONY : src/neural/integration/neural_bridge.mm.o

src/neural/integration/neural_bridge.i: src/neural/integration/neural_bridge.mm.i
.PHONY : src/neural/integration/neural_bridge.i

# target to preprocess a source file
src/neural/integration/neural_bridge.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/integration/neural_bridge.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/integration/neural_bridge.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/integration/neural_bridge.mm.i
.PHONY : src/neural/integration/neural_bridge.mm.i

src/neural/integration/neural_bridge.s: src/neural/integration/neural_bridge.mm.s
.PHONY : src/neural/integration/neural_bridge.s

# target to generate assembly for a file
src/neural/integration/neural_bridge.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/integration/neural_bridge.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/integration/neural_bridge.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/integration/neural_bridge.mm.s
.PHONY : src/neural/integration/neural_bridge.mm.s

src/neural/integration/neural_bridge_enhanced.o: src/neural/integration/neural_bridge_enhanced.c.o
.PHONY : src/neural/integration/neural_bridge_enhanced.o

# target to build an object file
src/neural/integration/neural_bridge_enhanced.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/integration/neural_bridge_enhanced.c.o
.PHONY : src/neural/integration/neural_bridge_enhanced.c.o

src/neural/integration/neural_bridge_enhanced.i: src/neural/integration/neural_bridge_enhanced.c.i
.PHONY : src/neural/integration/neural_bridge_enhanced.i

# target to preprocess a source file
src/neural/integration/neural_bridge_enhanced.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/integration/neural_bridge_enhanced.c.i
.PHONY : src/neural/integration/neural_bridge_enhanced.c.i

src/neural/integration/neural_bridge_enhanced.s: src/neural/integration/neural_bridge_enhanced.c.s
.PHONY : src/neural/integration/neural_bridge_enhanced.s

# target to generate assembly for a file
src/neural/integration/neural_bridge_enhanced.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/integration/neural_bridge_enhanced.c.s
.PHONY : src/neural/integration/neural_bridge_enhanced.c.s

src/neural/integration/neural_bridge_lossless_cuda.o: src/neural/integration/neural_bridge_lossless_cuda.mm.o
.PHONY : src/neural/integration/neural_bridge_lossless_cuda.o

# target to build an object file
src/neural/integration/neural_bridge_lossless_cuda.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/integration/neural_bridge_lossless_cuda.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/integration/neural_bridge_lossless_cuda.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/integration/neural_bridge_lossless_cuda.mm.o
.PHONY : src/neural/integration/neural_bridge_lossless_cuda.mm.o

src/neural/integration/neural_bridge_lossless_cuda.i: src/neural/integration/neural_bridge_lossless_cuda.mm.i
.PHONY : src/neural/integration/neural_bridge_lossless_cuda.i

# target to preprocess a source file
src/neural/integration/neural_bridge_lossless_cuda.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/integration/neural_bridge_lossless_cuda.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/integration/neural_bridge_lossless_cuda.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/integration/neural_bridge_lossless_cuda.mm.i
.PHONY : src/neural/integration/neural_bridge_lossless_cuda.mm.i

src/neural/integration/neural_bridge_lossless_cuda.s: src/neural/integration/neural_bridge_lossless_cuda.mm.s
.PHONY : src/neural/integration/neural_bridge_lossless_cuda.s

# target to generate assembly for a file
src/neural/integration/neural_bridge_lossless_cuda.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/integration/neural_bridge_lossless_cuda.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/integration/neural_bridge_lossless_cuda.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/integration/neural_bridge_lossless_cuda.mm.s
.PHONY : src/neural/integration/neural_bridge_lossless_cuda.mm.s

src/neural/lstm/nncp_lstm_metal_enhanced.o: src/neural/lstm/nncp_lstm_metal_enhanced.mm.o
.PHONY : src/neural/lstm/nncp_lstm_metal_enhanced.o

# target to build an object file
src/neural/lstm/nncp_lstm_metal_enhanced.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/lstm/nncp_lstm_metal_enhanced.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/lstm/nncp_lstm_metal_enhanced.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/lstm/nncp_lstm_metal_enhanced.mm.o
.PHONY : src/neural/lstm/nncp_lstm_metal_enhanced.mm.o

src/neural/lstm/nncp_lstm_metal_enhanced.i: src/neural/lstm/nncp_lstm_metal_enhanced.mm.i
.PHONY : src/neural/lstm/nncp_lstm_metal_enhanced.i

# target to preprocess a source file
src/neural/lstm/nncp_lstm_metal_enhanced.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/lstm/nncp_lstm_metal_enhanced.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/lstm/nncp_lstm_metal_enhanced.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/lstm/nncp_lstm_metal_enhanced.mm.i
.PHONY : src/neural/lstm/nncp_lstm_metal_enhanced.mm.i

src/neural/lstm/nncp_lstm_metal_enhanced.s: src/neural/lstm/nncp_lstm_metal_enhanced.mm.s
.PHONY : src/neural/lstm/nncp_lstm_metal_enhanced.s

# target to generate assembly for a file
src/neural/lstm/nncp_lstm_metal_enhanced.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/lstm/nncp_lstm_metal_enhanced.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/lstm/nncp_lstm_metal_enhanced.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/lstm/nncp_lstm_metal_enhanced.mm.s
.PHONY : src/neural/lstm/nncp_lstm_metal_enhanced.mm.s

src/neural/ops/nncp_lstm_metal.o: src/neural/ops/nncp_lstm_metal.mm.o
.PHONY : src/neural/ops/nncp_lstm_metal.o

# target to build an object file
src/neural/ops/nncp_lstm_metal.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/ops/nncp_lstm_metal.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/ops/nncp_lstm_metal.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/ops/nncp_lstm_metal.mm.o
.PHONY : src/neural/ops/nncp_lstm_metal.mm.o

src/neural/ops/nncp_lstm_metal.i: src/neural/ops/nncp_lstm_metal.mm.i
.PHONY : src/neural/ops/nncp_lstm_metal.i

# target to preprocess a source file
src/neural/ops/nncp_lstm_metal.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/ops/nncp_lstm_metal.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/ops/nncp_lstm_metal.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/ops/nncp_lstm_metal.mm.i
.PHONY : src/neural/ops/nncp_lstm_metal.mm.i

src/neural/ops/nncp_lstm_metal.s: src/neural/ops/nncp_lstm_metal.mm.s
.PHONY : src/neural/ops/nncp_lstm_metal.s

# target to generate assembly for a file
src/neural/ops/nncp_lstm_metal.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/ops/nncp_lstm_metal.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/ops/nncp_lstm_metal.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/ops/nncp_lstm_metal.mm.s
.PHONY : src/neural/ops/nncp_lstm_metal.mm.s

src/neural/ops/nncp_lstm_prediction.o: src/neural/ops/nncp_lstm_prediction.mm.o
.PHONY : src/neural/ops/nncp_lstm_prediction.o

# target to build an object file
src/neural/ops/nncp_lstm_prediction.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/ops/nncp_lstm_prediction.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/ops/nncp_lstm_prediction.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/ops/nncp_lstm_prediction.mm.o
.PHONY : src/neural/ops/nncp_lstm_prediction.mm.o

src/neural/ops/nncp_lstm_prediction.i: src/neural/ops/nncp_lstm_prediction.mm.i
.PHONY : src/neural/ops/nncp_lstm_prediction.i

# target to preprocess a source file
src/neural/ops/nncp_lstm_prediction.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/ops/nncp_lstm_prediction.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/ops/nncp_lstm_prediction.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/ops/nncp_lstm_prediction.mm.i
.PHONY : src/neural/ops/nncp_lstm_prediction.mm.i

src/neural/ops/nncp_lstm_prediction.s: src/neural/ops/nncp_lstm_prediction.mm.s
.PHONY : src/neural/ops/nncp_lstm_prediction.s

# target to generate assembly for a file
src/neural/ops/nncp_lstm_prediction.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/ops/nncp_lstm_prediction.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/ops/nncp_lstm_prediction.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/ops/nncp_lstm_prediction.mm.s
.PHONY : src/neural/ops/nncp_lstm_prediction.mm.s

src/neural/ops/nncp_lstm_state_manager.o: src/neural/ops/nncp_lstm_state_manager.mm.o
.PHONY : src/neural/ops/nncp_lstm_state_manager.o

# target to build an object file
src/neural/ops/nncp_lstm_state_manager.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/ops/nncp_lstm_state_manager.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/ops/nncp_lstm_state_manager.mm.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/ops/nncp_lstm_state_manager.mm.o
.PHONY : src/neural/ops/nncp_lstm_state_manager.mm.o

src/neural/ops/nncp_lstm_state_manager.i: src/neural/ops/nncp_lstm_state_manager.mm.i
.PHONY : src/neural/ops/nncp_lstm_state_manager.i

# target to preprocess a source file
src/neural/ops/nncp_lstm_state_manager.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/ops/nncp_lstm_state_manager.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/ops/nncp_lstm_state_manager.mm.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/ops/nncp_lstm_state_manager.mm.i
.PHONY : src/neural/ops/nncp_lstm_state_manager.mm.i

src/neural/ops/nncp_lstm_state_manager.s: src/neural/ops/nncp_lstm_state_manager.mm.s
.PHONY : src/neural/ops/nncp_lstm_state_manager.s

# target to generate assembly for a file
src/neural/ops/nncp_lstm_state_manager.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/ops/nncp_lstm_state_manager.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/ops/nncp_lstm_state_manager.mm.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/ops/nncp_lstm_state_manager.mm.s
.PHONY : src/neural/ops/nncp_lstm_state_manager.mm.s

src/neural/prediction/entropy_analyzer.o: src/neural/prediction/entropy_analyzer.c.o
.PHONY : src/neural/prediction/entropy_analyzer.o

# target to build an object file
src/neural/prediction/entropy_analyzer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/prediction/entropy_analyzer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/prediction/entropy_analyzer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/prediction/entropy_analyzer.c.o
.PHONY : src/neural/prediction/entropy_analyzer.c.o

src/neural/prediction/entropy_analyzer.i: src/neural/prediction/entropy_analyzer.c.i
.PHONY : src/neural/prediction/entropy_analyzer.i

# target to preprocess a source file
src/neural/prediction/entropy_analyzer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/prediction/entropy_analyzer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/prediction/entropy_analyzer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/prediction/entropy_analyzer.c.i
.PHONY : src/neural/prediction/entropy_analyzer.c.i

src/neural/prediction/entropy_analyzer.s: src/neural/prediction/entropy_analyzer.c.s
.PHONY : src/neural/prediction/entropy_analyzer.s

# target to generate assembly for a file
src/neural/prediction/entropy_analyzer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/prediction/entropy_analyzer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/prediction/entropy_analyzer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/prediction/entropy_analyzer.c.s
.PHONY : src/neural/prediction/entropy_analyzer.c.s

src/neural/prediction/pattern_matcher.o: src/neural/prediction/pattern_matcher.c.o
.PHONY : src/neural/prediction/pattern_matcher.o

# target to build an object file
src/neural/prediction/pattern_matcher.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/prediction/pattern_matcher.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/prediction/pattern_matcher.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/prediction/pattern_matcher.c.o
.PHONY : src/neural/prediction/pattern_matcher.c.o

src/neural/prediction/pattern_matcher.i: src/neural/prediction/pattern_matcher.c.i
.PHONY : src/neural/prediction/pattern_matcher.i

# target to preprocess a source file
src/neural/prediction/pattern_matcher.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/prediction/pattern_matcher.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/prediction/pattern_matcher.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/prediction/pattern_matcher.c.i
.PHONY : src/neural/prediction/pattern_matcher.c.i

src/neural/prediction/pattern_matcher.s: src/neural/prediction/pattern_matcher.c.s
.PHONY : src/neural/prediction/pattern_matcher.s

# target to generate assembly for a file
src/neural/prediction/pattern_matcher.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/prediction/pattern_matcher.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/prediction/pattern_matcher.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/prediction/pattern_matcher.c.s
.PHONY : src/neural/prediction/pattern_matcher.c.s

src/neural/prediction/prediction_scorer.o: src/neural/prediction/prediction_scorer.c.o
.PHONY : src/neural/prediction/prediction_scorer.o

# target to build an object file
src/neural/prediction/prediction_scorer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/prediction/prediction_scorer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/prediction/prediction_scorer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/prediction/prediction_scorer.c.o
.PHONY : src/neural/prediction/prediction_scorer.c.o

src/neural/prediction/prediction_scorer.i: src/neural/prediction/prediction_scorer.c.i
.PHONY : src/neural/prediction/prediction_scorer.i

# target to preprocess a source file
src/neural/prediction/prediction_scorer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/prediction/prediction_scorer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/prediction/prediction_scorer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/prediction/prediction_scorer.c.i
.PHONY : src/neural/prediction/prediction_scorer.c.i

src/neural/prediction/prediction_scorer.s: src/neural/prediction/prediction_scorer.c.s
.PHONY : src/neural/prediction/prediction_scorer.s

# target to generate assembly for a file
src/neural/prediction/prediction_scorer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/prediction/prediction_scorer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/prediction/prediction_scorer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/prediction/prediction_scorer.c.s
.PHONY : src/neural/prediction/prediction_scorer.c.s

src/neural/quality/quality_validator.o: src/neural/quality/quality_validator.c.o
.PHONY : src/neural/quality/quality_validator.o

# target to build an object file
src/neural/quality/quality_validator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/quality/quality_validator.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/quality/quality_validator.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/quality/quality_validator.c.o
.PHONY : src/neural/quality/quality_validator.c.o

src/neural/quality/quality_validator.i: src/neural/quality/quality_validator.c.i
.PHONY : src/neural/quality/quality_validator.i

# target to preprocess a source file
src/neural/quality/quality_validator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/quality/quality_validator.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/quality/quality_validator.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/quality/quality_validator.c.i
.PHONY : src/neural/quality/quality_validator.c.i

src/neural/quality/quality_validator.s: src/neural/quality/quality_validator.c.s
.PHONY : src/neural/quality/quality_validator.s

# target to generate assembly for a file
src/neural/quality/quality_validator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/quality/quality_validator.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/quality/quality_validator.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/quality/quality_validator.c.s
.PHONY : src/neural/quality/quality_validator.c.s

src/neural/selection/content_analyzer.o: src/neural/selection/content_analyzer.c.o
.PHONY : src/neural/selection/content_analyzer.o

# target to build an object file
src/neural/selection/content_analyzer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/selection/content_analyzer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/selection/content_analyzer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/selection/content_analyzer.c.o
.PHONY : src/neural/selection/content_analyzer.c.o

src/neural/selection/content_analyzer.i: src/neural/selection/content_analyzer.c.i
.PHONY : src/neural/selection/content_analyzer.i

# target to preprocess a source file
src/neural/selection/content_analyzer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/selection/content_analyzer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/selection/content_analyzer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/selection/content_analyzer.c.i
.PHONY : src/neural/selection/content_analyzer.c.i

src/neural/selection/content_analyzer.s: src/neural/selection/content_analyzer.c.s
.PHONY : src/neural/selection/content_analyzer.s

# target to generate assembly for a file
src/neural/selection/content_analyzer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/selection/content_analyzer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/selection/content_analyzer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/selection/content_analyzer.c.s
.PHONY : src/neural/selection/content_analyzer.c.s

src/neural/selection/enhanced_selector.o: src/neural/selection/enhanced_selector.c.o
.PHONY : src/neural/selection/enhanced_selector.o

# target to build an object file
src/neural/selection/enhanced_selector.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/selection/enhanced_selector.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/selection/enhanced_selector.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/selection/enhanced_selector.c.o
.PHONY : src/neural/selection/enhanced_selector.c.o

src/neural/selection/enhanced_selector.i: src/neural/selection/enhanced_selector.c.i
.PHONY : src/neural/selection/enhanced_selector.i

# target to preprocess a source file
src/neural/selection/enhanced_selector.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/selection/enhanced_selector.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/selection/enhanced_selector.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/selection/enhanced_selector.c.i
.PHONY : src/neural/selection/enhanced_selector.c.i

src/neural/selection/enhanced_selector.s: src/neural/selection/enhanced_selector.c.s
.PHONY : src/neural/selection/enhanced_selector.s

# target to generate assembly for a file
src/neural/selection/enhanced_selector.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/selection/enhanced_selector.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-diagnostics.dir/build.make CMakeFiles/nncp-diagnostics.dir/src/neural/selection/enhanced_selector.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/src/neural/selection/enhanced_selector.c.s
.PHONY : src/neural/selection/enhanced_selector.c.s

src/neural/validation/cuda_parameter_validator.o: src/neural/validation/cuda_parameter_validator.c.o
.PHONY : src/neural/validation/cuda_parameter_validator.o

# target to build an object file
src/neural/validation/cuda_parameter_validator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/validation/cuda_parameter_validator.c.o
.PHONY : src/neural/validation/cuda_parameter_validator.c.o

src/neural/validation/cuda_parameter_validator.i: src/neural/validation/cuda_parameter_validator.c.i
.PHONY : src/neural/validation/cuda_parameter_validator.i

# target to preprocess a source file
src/neural/validation/cuda_parameter_validator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/validation/cuda_parameter_validator.c.i
.PHONY : src/neural/validation/cuda_parameter_validator.c.i

src/neural/validation/cuda_parameter_validator.s: src/neural/validation/cuda_parameter_validator.c.s
.PHONY : src/neural/validation/cuda_parameter_validator.s

# target to generate assembly for a file
src/neural/validation/cuda_parameter_validator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nncp-metal.dir/build.make CMakeFiles/nncp-metal.dir/src/neural/validation/cuda_parameter_validator.c.s
.PHONY : src/neural/validation/cuda_parameter_validator.c.s

tests/cuda_compatibility_tests_simple.o: tests/cuda_compatibility_tests_simple.c.o
.PHONY : tests/cuda_compatibility_tests_simple.o

# target to build an object file
tests/cuda_compatibility_tests_simple.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/tests/cuda_compatibility_tests_simple.c.o
.PHONY : tests/cuda_compatibility_tests_simple.c.o

tests/cuda_compatibility_tests_simple.i: tests/cuda_compatibility_tests_simple.c.i
.PHONY : tests/cuda_compatibility_tests_simple.i

# target to preprocess a source file
tests/cuda_compatibility_tests_simple.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/tests/cuda_compatibility_tests_simple.c.i
.PHONY : tests/cuda_compatibility_tests_simple.c.i

tests/cuda_compatibility_tests_simple.s: tests/cuda_compatibility_tests_simple.c.s
.PHONY : tests/cuda_compatibility_tests_simple.s

# target to generate assembly for a file
tests/cuda_compatibility_tests_simple.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cuda-compatibility-tests.dir/build.make CMakeFiles/cuda-compatibility-tests.dir/tests/cuda_compatibility_tests_simple.c.s
.PHONY : tests/cuda_compatibility_tests_simple.c.s

tests/test_compression_integration.o: tests/test_compression_integration.c.o
.PHONY : tests/test_compression_integration.o

# target to build an object file
tests/test_compression_integration.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/tests/test_compression_integration.c.o
.PHONY : tests/test_compression_integration.c.o

tests/test_compression_integration.i: tests/test_compression_integration.c.i
.PHONY : tests/test_compression_integration.i

# target to preprocess a source file
tests/test_compression_integration.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/tests/test_compression_integration.c.i
.PHONY : tests/test_compression_integration.c.i

tests/test_compression_integration.s: tests/test_compression_integration.c.s
.PHONY : tests/test_compression_integration.s

# target to generate assembly for a file
tests/test_compression_integration.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test-compression-integration.dir/build.make CMakeFiles/test-compression-integration.dir/tests/test_compression_integration.c.s
.PHONY : tests/test_compression_integration.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... metal_shaders"
	@echo "... cuda-compatibility-tests"
	@echo "... nncp-diagnostics"
	@echo "... nncp-metal"
	@echo "... nncp_tests"
	@echo "... test-compression-integration"
	@echo "... test_bpe_tokenizer"
	@echo "... test_compression_selector"
	@echo "... test_coreml_loader"
	@echo "... test_enhanced_format"
	@echo "... test_mps_attention"
	@echo "... test_mps_lstm"
	@echo "... test_mps_transformer"
	@echo "... test_performance_monitor"
	@echo "... test_quality_validator"
	@echo "... test_sequence_manager"
	@echo "... src/metal/algorithm_router.o"
	@echo "... src/metal/algorithm_router.i"
	@echo "... src/metal/algorithm_router.s"
	@echo "... src/metal/compression_integration.o"
	@echo "... src/metal/compression_integration.i"
	@echo "... src/metal/compression_integration.s"
	@echo "... src/metal/compression_selector_stub.o"
	@echo "... src/metal/compression_selector_stub.i"
	@echo "... src/metal/compression_selector_stub.s"
	@echo "... src/metal/nncp_diagnostics.o"
	@echo "... src/metal/nncp_diagnostics.i"
	@echo "... src/metal/nncp_diagnostics.s"
	@echo "... src/metal/nncp_metal.o"
	@echo "... src/metal/nncp_metal.i"
	@echo "... src/metal/nncp_metal.s"
	@echo "... src/metal/nncp_original_port.o"
	@echo "... src/metal/nncp_original_port.i"
	@echo "... src/metal/nncp_original_port.s"
	@echo "... src/metal/wrapper/compute_kernels.o"
	@echo "... src/metal/wrapper/compute_kernels.i"
	@echo "... src/metal/wrapper/compute_kernels.s"
	@echo "... src/metal/wrapper/memory_manager.o"
	@echo "... src/metal/wrapper/memory_manager.i"
	@echo "... src/metal/wrapper/memory_manager.s"
	@echo "... src/metal/wrapper/metal_buffers.o"
	@echo "... src/metal/wrapper/metal_buffers.i"
	@echo "... src/metal/wrapper/metal_buffers.s"
	@echo "... src/metal/wrapper/metal_context.o"
	@echo "... src/metal/wrapper/metal_context.i"
	@echo "... src/metal/wrapper/metal_context.s"
	@echo "... src/metal/wrapper/metal_kernels.o"
	@echo "... src/metal/wrapper/metal_kernels.i"
	@echo "... src/metal/wrapper/metal_kernels.s"
	@echo "... src/metal/wrapper/neural_engine.o"
	@echo "... src/metal/wrapper/neural_engine.i"
	@echo "... src/metal/wrapper/neural_engine.s"
	@echo "... src/neural/compatibility/cuda_math_compat.o"
	@echo "... src/neural/compatibility/cuda_math_compat.i"
	@echo "... src/neural/compatibility/cuda_math_compat.s"
	@echo "... src/neural/config/cuda_profiles.o"
	@echo "... src/neural/config/cuda_profiles.i"
	@echo "... src/neural/config/cuda_profiles.s"
	@echo "... src/neural/context/dynamic_context.o"
	@echo "... src/neural/context/dynamic_context.i"
	@echo "... src/neural/context/dynamic_context.s"
	@echo "... src/neural/error/cuda_error_handler.o"
	@echo "... src/neural/error/cuda_error_handler.i"
	@echo "... src/neural/error/cuda_error_handler.s"
	@echo "... src/neural/handlers/small_file_handler.o"
	@echo "... src/neural/handlers/small_file_handler.i"
	@echo "... src/neural/handlers/small_file_handler.s"
	@echo "... src/neural/integration/neural_bridge.o"
	@echo "... src/neural/integration/neural_bridge.i"
	@echo "... src/neural/integration/neural_bridge.s"
	@echo "... src/neural/integration/neural_bridge_enhanced.o"
	@echo "... src/neural/integration/neural_bridge_enhanced.i"
	@echo "... src/neural/integration/neural_bridge_enhanced.s"
	@echo "... src/neural/integration/neural_bridge_lossless_cuda.o"
	@echo "... src/neural/integration/neural_bridge_lossless_cuda.i"
	@echo "... src/neural/integration/neural_bridge_lossless_cuda.s"
	@echo "... src/neural/lstm/nncp_lstm_metal_enhanced.o"
	@echo "... src/neural/lstm/nncp_lstm_metal_enhanced.i"
	@echo "... src/neural/lstm/nncp_lstm_metal_enhanced.s"
	@echo "... src/neural/ops/nncp_lstm_metal.o"
	@echo "... src/neural/ops/nncp_lstm_metal.i"
	@echo "... src/neural/ops/nncp_lstm_metal.s"
	@echo "... src/neural/ops/nncp_lstm_prediction.o"
	@echo "... src/neural/ops/nncp_lstm_prediction.i"
	@echo "... src/neural/ops/nncp_lstm_prediction.s"
	@echo "... src/neural/ops/nncp_lstm_state_manager.o"
	@echo "... src/neural/ops/nncp_lstm_state_manager.i"
	@echo "... src/neural/ops/nncp_lstm_state_manager.s"
	@echo "... src/neural/prediction/entropy_analyzer.o"
	@echo "... src/neural/prediction/entropy_analyzer.i"
	@echo "... src/neural/prediction/entropy_analyzer.s"
	@echo "... src/neural/prediction/pattern_matcher.o"
	@echo "... src/neural/prediction/pattern_matcher.i"
	@echo "... src/neural/prediction/pattern_matcher.s"
	@echo "... src/neural/prediction/prediction_scorer.o"
	@echo "... src/neural/prediction/prediction_scorer.i"
	@echo "... src/neural/prediction/prediction_scorer.s"
	@echo "... src/neural/quality/quality_validator.o"
	@echo "... src/neural/quality/quality_validator.i"
	@echo "... src/neural/quality/quality_validator.s"
	@echo "... src/neural/selection/content_analyzer.o"
	@echo "... src/neural/selection/content_analyzer.i"
	@echo "... src/neural/selection/content_analyzer.s"
	@echo "... src/neural/selection/enhanced_selector.o"
	@echo "... src/neural/selection/enhanced_selector.i"
	@echo "... src/neural/selection/enhanced_selector.s"
	@echo "... src/neural/validation/cuda_parameter_validator.o"
	@echo "... src/neural/validation/cuda_parameter_validator.i"
	@echo "... src/neural/validation/cuda_parameter_validator.s"
	@echo "... tests/cuda_compatibility_tests_simple.o"
	@echo "... tests/cuda_compatibility_tests_simple.i"
	@echo "... tests/cuda_compatibility_tests_simple.s"
	@echo "... tests/test_compression_integration.o"
	@echo "... tests/test_compression_integration.i"
	@echo "... tests/test_compression_integration.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

